pipeline{
    agent any
       tools{
        maven 'maven_3_8_6'
       }
       stages {
        stage("Build Maven") {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/fpardopoli/Integracion-Continua']]])
                sh 'mvn clean install'
            }
         }
         stage("Build docker image"){
           steps{
             script {
                sh 'docker compose -f "docker-compose.yml" down '
                sh 'docker compose  -f "docker-compose.yml" up -d --build sqldata user '
             }
           }
         }
       }
 
}